# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yuchen's Blog
email: anthony.yuchen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Yuchen Zhang's Personal Blog. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://anthonyive.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: anthonyive
github_username:  anthonyive

author: Yuchen Zhang

# Build settings
remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-feed

figures:
  dir: /blog/assets/figures
  enumerate: true
  analytics: tru

copyright: Copyright © 2021

# If you want to generate website sitemap, you can set true
sitemap: true

# Pagination setting
paginate: 10

# Disqus comments
disqus:
  shortname: "blog-g49frf6rg4"

# Google analytics
google_analytics: "UA-199968139-1"
enableDNT: "false"

# Gitment comments
# gitment:
#   username: "anthonyive"
#   repo: "blog"
#   client_id: "7431df1dff02a966279e"
#   client_secret: "08868c03bdb2f8504995c1463c93ebe1f4bf7d9f"
#   redirect_uri: "https://anthonyive.github.io/blog/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
